# Generated by Django 4.2.4 on 2023-08-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MagentoProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.BigIntegerField(help_text="entity_id", max_length=250),
                ),
                ("tipo", models.CharField(help_text="tipo", max_length=250)),
                ("sku", models.CharField(help_text="sku", max_length=250)),
                ("fecha_creacion", models.DateTimeField(help_text="fecha creacion")),
                (
                    "Tipo_impuesto",
                    models.CharField(help_text="Impuesto", max_length=250),
                ),
                ("nombre", models.CharField(help_text="nombre", max_length=250)),
                ("url", models.CharField(help_text="url", max_length=250)),
                ("estado", models.CharField(help_text="estado", max_length=250)),
                ("precio", models.BigIntegerField(help_text="precio", max_length=250)),
                (
                    "precio_especial",
                    models.BigIntegerField(help_text="precio_especial", max_length=250),
                ),
                (
                    "p_especial_desde",
                    models.DateTimeField(help_text="p_especial_desde", max_length=250),
                ),
                (
                    "p_especial_hasta",
                    models.DateTimeField(help_text="p_especial_hasta", max_length=250),
                ),
                (
                    "visibilidad",
                    models.CharField(help_text="visibilidad", max_length=250),
                ),
                (
                    "cantidad",
                    models.BigIntegerField(help_text="cantidad", max_length=250),
                ),
                (
                    "esta_en_stock",
                    models.CharField(help_text="esta_en_stock", max_length=250),
                ),
                ("peso", models.FloatField(help_text="peso", max_length=250)),
                (
                    "short_description",
                    models.CharField(help_text="short_description", max_length=1000),
                ),
                (
                    "description",
                    models.CharField(help_text="description", max_length=1000),
                ),
                (
                    "meta_titulo",
                    models.CharField(help_text="meta_titulo", max_length=250),
                ),
                (
                    "meta_descripcion",
                    models.CharField(help_text="meta_descripcion", max_length=255),
                ),
                ("imagen", models.CharField(help_text="imagen", max_length=255)),
                ("imagen2", models.CharField(help_text="imagen2", max_length=255)),
                (
                    "category_list",
                    models.CharField(help_text="category_list", max_length=255),
                ),
            ],
            options={
                "verbose_name": "MagentoProducts",
                "verbose_name_plural": "MagentoProductss",
            },
        ),
    ]
