# Generated by Django 4.2.4 on 2023-08-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magentoproducts",
            name="description",
            field=models.TextField(help_text="description"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="meta_descripcion",
            field=models.TextField(help_text="meta_descripcion"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="meta_titulo",
            field=models.TextField(help_text="meta_titulo"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="short_description",
            field=models.TextField(help_text="short_description"),
        ),
    ]
