# Generated by Django 4.2.4 on 2023-08-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0002_alter_magentoproducts_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magentoproducts",
            name="meta_titulo",
            field=models.TextField(blank=True, help_text="meta_titulo", null=True),
        ),
    ]
