# Generated by Django 4.2.4 on 2023-08-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0003_alter_magentoproducts_meta_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magentoproducts",
            name="cantidad",
            field=models.BigIntegerField(help_text="cantidad"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="entity_id",
            field=models.BigIntegerField(help_text="entity_id"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="precio",
            field=models.BigIntegerField(help_text="precio"),
        ),
        migrations.AlterField(
            model_name="magentoproducts",
            name="precio_especial",
            field=models.BigIntegerField(help_text="precio_especial"),
        ),
    ]
