# Generated by Django 4.2.4 on 2023-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0006_alter_magentoproducts_tipo_impuesto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="magentoproducts",
            name="color",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
