# Generated by Django 4.2.4 on 2023-08-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0007_magentoproducts_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magentoproducts",
            name="category_list",
            field=models.TextField(help_text="category_list", null=True),
        ),
    ]
