# Generated by Django 4.2.4 on 2023-08-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0009_magentoproducts_medidas"),
    ]

    operations = [
        migrations.AddField(
            model_name="magentoproducts",
            name="pais",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
