# Generated by Django 4.2.4 on 2023-08-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0010_magentoproducts_pais"),
    ]

    operations = [
        migrations.AddField(
            model_name="magentoproducts",
            name="garantia",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
