# Generated by Django 4.2.4 on 2023-08-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magento", "0011_magentoproducts_garantia"),
    ]

    operations = [
        migrations.AddField(
            model_name="magentoproducts",
            name="marca",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
